# Generated by Django 4.1.5 on 2023-10-08 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_number', models.IntegerField()),
                ('First_name', models.CharField(max_length=200)),
                ('Last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('Program_type_1', models.CharField(choices=[('Single_Major', 'Single Major'), ('Major_Minor', 'Major-Minor'), ('Combined_Major', 'Combined Major')], max_length=200)),
                ('Program_type_2', models.CharField(choices=[('Single_Major', 'Single Major'), ('Major_Minor', 'Major-Minor'), ('Combined_Major', 'Combined Major')], max_length=200)),
                ('Program_type_3', models.CharField(choices=[('Single_Major', 'Single Major'), ('Major_Minor', 'Major-Minor'), ('Combined_Major', 'Combined Major')], max_length=200)),
                ('Program_1', models.CharField(choices=[('Actuarial Science', 'Actuarial Science'), ('Applied Geology', 'Applied Geology'), ('Applied Geophysics', 'Applied Geophysics'), ('Biomathematics', 'Biomathematics'), ('Chemistry', 'Chemistry'), ('Computer Science', 'Computer Science'), ('Geology', 'Geology'), ('Geophysics', 'Geophysics'), ('Information Technology', 'Information Technology'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Statistics', 'Statistics'), ('Computer Science with Mathematics', 'Computer Science with Mathematics'), ('Computer Science with Physics', 'Computer Science with Physics'), ('Computer Science with Statistics', 'Computer Science with Statistics'), ('Geology with Physics', 'Geology with Physics'), ('Geology with Mathematics', 'Geology with Mathematics'), ('Mathematics with Computer Science', 'Mathematics with Computer Science'), ('Mathematics with Physics', 'Mathematics with Physics'), ('Mathematics with Statistics', 'Mathematics with Statistics'), ('Mathematics with Geology', 'Mathematics with Geology'), ('Physics with Computer Science', 'Physics with Computer Science'), ('Physics with Geology', 'Physics with Geology'), ('Physics with Mathematics', 'Physics with Mathematics'), ('Statistics with Computer Science', 'Statistics with Computer Science'), ('Statistics with Mathematics', 'Statistics with Mathematics'), ('Physics with Statistics', 'Physics with Statistics'), ('Chemistry and a Biological Science programme', 'Chemistry and a Biological Science programme'), ('Chemistry and Physics', 'Chemistry and Physics'), ('Computer Science and Mathematics', 'Computer Science and Mathematics'), ('Computer Science and Statistics', 'Computer Science and Statistics'), ('Computer Science and Physics', 'Computer Science and Physics'), ('Mathematics and Statistics', 'Mathematics and Statistics'), ('Physics and Mathematics', 'Physics and Mathematics'), ('Physics and Statistics', 'Physics and Statistics')], max_length=200)),
                ('Program_2', models.CharField(choices=[('Actuarial Science', 'Actuarial Science'), ('Applied Geology', 'Applied Geology'), ('Applied Geophysics', 'Applied Geophysics'), ('Biomathematics', 'Biomathematics'), ('Chemistry', 'Chemistry'), ('Computer Science', 'Computer Science'), ('Geology', 'Geology'), ('Geophysics', 'Geophysics'), ('Information Technology', 'Information Technology'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Statistics', 'Statistics'), ('Computer Science with Mathematics', 'Computer Science with Mathematics'), ('Computer Science with Physics', 'Computer Science with Physics'), ('Computer Science with Statistics', 'Computer Science with Statistics'), ('Geology with Physics', 'Geology with Physics'), ('Geology with Mathematics', 'Geology with Mathematics'), ('Mathematics with Computer Science', 'Mathematics with Computer Science'), ('Mathematics with Physics', 'Mathematics with Physics'), ('Mathematics with Statistics', 'Mathematics with Statistics'), ('Mathematics with Geology', 'Mathematics with Geology'), ('Physics with Computer Science', 'Physics with Computer Science'), ('Physics with Geology', 'Physics with Geology'), ('Physics with Mathematics', 'Physics with Mathematics'), ('Statistics with Computer Science', 'Statistics with Computer Science'), ('Statistics with Mathematics', 'Statistics with Mathematics'), ('Physics with Statistics', 'Physics with Statistics'), ('Chemistry and a Biological Science programme', 'Chemistry and a Biological Science programme'), ('Chemistry and Physics', 'Chemistry and Physics'), ('Computer Science and Mathematics', 'Computer Science and Mathematics'), ('Computer Science and Statistics', 'Computer Science and Statistics'), ('Computer Science and Physics', 'Computer Science and Physics'), ('Mathematics and Statistics', 'Mathematics and Statistics'), ('Physics and Mathematics', 'Physics and Mathematics'), ('Physics and Statistics', 'Physics and Statistics')], max_length=200)),
                ('Program_3', models.CharField(choices=[('Actuarial Science', 'Actuarial Science'), ('Applied Geology', 'Applied Geology'), ('Applied Geophysics', 'Applied Geophysics'), ('Biomathematics', 'Biomathematics'), ('Chemistry', 'Chemistry'), ('Computer Science', 'Computer Science'), ('Geology', 'Geology'), ('Geophysics', 'Geophysics'), ('Information Technology', 'Information Technology'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Statistics', 'Statistics'), ('Computer Science with Mathematics', 'Computer Science with Mathematics'), ('Computer Science with Physics', 'Computer Science with Physics'), ('Computer Science with Statistics', 'Computer Science with Statistics'), ('Geology with Physics', 'Geology with Physics'), ('Geology with Mathematics', 'Geology with Mathematics'), ('Mathematics with Computer Science', 'Mathematics with Computer Science'), ('Mathematics with Physics', 'Mathematics with Physics'), ('Mathematics with Statistics', 'Mathematics with Statistics'), ('Mathematics with Geology', 'Mathematics with Geology'), ('Physics with Computer Science', 'Physics with Computer Science'), ('Physics with Geology', 'Physics with Geology'), ('Physics with Mathematics', 'Physics with Mathematics'), ('Statistics with Computer Science', 'Statistics with Computer Science'), ('Statistics with Mathematics', 'Statistics with Mathematics'), ('Physics with Statistics', 'Physics with Statistics'), ('Chemistry and a Biological Science programme', 'Chemistry and a Biological Science programme'), ('Chemistry and Physics', 'Chemistry and Physics'), ('Computer Science and Mathematics', 'Computer Science and Mathematics'), ('Computer Science and Statistics', 'Computer Science and Statistics'), ('Computer Science and Physics', 'Computer Science and Physics'), ('Mathematics and Statistics', 'Mathematics and Statistics'), ('Physics and Mathematics', 'Physics and Mathematics'), ('Physics and Statistics', 'Physics and Statistics')], max_length=200)),
                ('DCIT101', models.CharField(choices=[('1', 'N/A'), ('2', 'A'), ('3', 'B+'), ('4', 'B'), ('5', 'C+'), ('6', 'C'), ('7', 'D+'), ('8', 'D'), ('9', 'E'), ('10', 'F')], default='N/A', max_length=100)),
                ('DCIT102', models.CharField(choices=[('1', 'N/A'), ('2', 'A'), ('3', 'B+'), ('4', 'B'), ('5', 'C+'), ('6', 'C'), ('7', 'D+'), ('8', 'D'), ('9', 'E'), ('10', 'F')], default='N/A', max_length=100)),
                ('DCIT103', models.CharField(choices=[('1', 'N/A'), ('2', 'A'), ('3', 'B+'), ('4', 'B'), ('5', 'C+'), ('6', 'C'), ('7', 'D+'), ('8', 'D'), ('9', 'E'), ('10', 'F')], default='N/A', max_length=100)),
                ('DCIT104', models.CharField(choices=[('1', 'N/A'), ('2', 'A'), ('3', 'B+'), ('4', 'B'), ('5', 'C+'), ('6', 'C'), ('7', 'D+'), ('8', 'D'), ('9', 'E'), ('10', 'F')], default='N/A', max_length=100)),
                ('MATH121', models.CharField(choices=[('1', 'N/A'), ('2', 'A'), ('3', 'B+'), ('4', 'B'), ('5', 'C+'), ('6', 'C'), ('7', 'D+'), ('8', 'D'), ('9', 'E'), ('10', 'F')], default='N/A', max_length=100)),
                ('MATH122', models.CharField(choices=[('1', 'N/A'), ('2', 'A'), ('3', 'B+'), ('4', 'B'), ('5', 'C+'), ('6', 'C'), ('7', 'D+'), ('8', 'D'), ('9', 'E'), ('10', 'F')], default='N/A', max_length=100)),
                ('MATH123', models.CharField(choices=[('1', 'N/A'), ('2', 'A'), ('3', 'B+'), ('4', 'B'), ('5', 'C+'), ('6', 'C'), ('7', 'D+'), ('8', 'D'), ('9', 'E'), ('10', 'F')], default='N/A', max_length=100)),
                ('MATH126', models.CharField(choices=[('1', 'N/A'), ('2', 'A'), ('3', 'B+'), ('4', 'B'), ('5', 'C+'), ('6', 'C'), ('7', 'D+'), ('8', 'D'), ('9', 'E'), ('10', 'F')], default='N/A', max_length=100)),
                ('STAT111', models.CharField(choices=[('1', 'N/A'), ('2', 'A'), ('3', 'B+'), ('4', 'B'), ('5', 'C+'), ('6', 'C'), ('7', 'D+'), ('8', 'D'), ('9', 'E'), ('10', 'F')], default='N/A', max_length=100)),
                ('STAT112', models.CharField(choices=[('1', 'N/A'), ('2', 'A'), ('3', 'B+'), ('4', 'B'), ('5', 'C+'), ('6', 'C'), ('7', 'D+'), ('8', 'D'), ('9', 'E'), ('10', 'F')], default='N/A', max_length=100)),
                ('PHYS105', models.CharField(choices=[('1', 'N/A'), ('2', 'A'), ('3', 'B+'), ('4', 'B'), ('5', 'C+'), ('6', 'C'), ('7', 'D+'), ('8', 'D'), ('9', 'E'), ('10', 'F')], default='N/A', max_length=100)),
                ('PHYS106', models.CharField(choices=[('1', 'N/A'), ('2', 'A'), ('3', 'B+'), ('4', 'B'), ('5', 'C+'), ('6', 'C'), ('7', 'D+'), ('8', 'D'), ('9', 'E'), ('10', 'F')], default='N/A', max_length=100)),
                ('PHYS143', models.CharField(choices=[('1', 'N/A'), ('2', 'A'), ('3', 'B+'), ('4', 'B'), ('5', 'C+'), ('6', 'C'), ('7', 'D+'), ('8', 'D'), ('9', 'E'), ('10', 'F')], default='N/A', max_length=100)),
                ('PHYS144', models.CharField(choices=[('1', 'N/A'), ('2', 'A'), ('3', 'B+'), ('4', 'B'), ('5', 'C+'), ('6', 'C'), ('7', 'D+'), ('8', 'D'), ('9', 'E'), ('10', 'F')], default='N/A', max_length=100)),
                ('ECON101', models.CharField(choices=[('1', 'N/A'), ('2', 'A'), ('3', 'B+'), ('4', 'B'), ('5', 'C+'), ('6', 'C'), ('7', 'D+'), ('8', 'D'), ('9', 'E'), ('10', 'F')], default='N/A', max_length=100)),
                ('ABCS101', models.CharField(choices=[('1', 'N/A'), ('2', 'A'), ('3', 'B+'), ('4', 'B'), ('5', 'C+'), ('6', 'C'), ('7', 'D+'), ('8', 'D'), ('9', 'E'), ('10', 'F')], default='N/A', max_length=100)),
                ('BOTN104', models.CharField(choices=[('1', 'N/A'), ('2', 'A'), ('3', 'B+'), ('4', 'B'), ('5', 'C+'), ('6', 'C'), ('7', 'D+'), ('8', 'D'), ('9', 'E'), ('10', 'F')], default='N/A', max_length=100)),
                ('CHEM113', models.CharField(choices=[('1', 'N/A'), ('2', 'A'), ('3', 'B+'), ('4', 'B'), ('5', 'C+'), ('6', 'C'), ('7', 'D+'), ('8', 'D'), ('9', 'E'), ('10', 'F')], default='N/A', max_length=100)),
                ('CHEM114', models.CharField(choices=[('1', 'N/A'), ('2', 'A'), ('3', 'B+'), ('4', 'B'), ('5', 'C+'), ('6', 'C'), ('7', 'D+'), ('8', 'D'), ('9', 'E'), ('10', 'F')], default='N/A', max_length=100)),
                ('CHEM120', models.CharField(choices=[('1', 'N/A'), ('2', 'A'), ('3', 'B+'), ('4', 'B'), ('5', 'C+'), ('6', 'C'), ('7', 'D+'), ('8', 'D'), ('9', 'E'), ('10', 'F')], default='N/A', max_length=100)),
                ('CHEM122', models.CharField(choices=[('1', 'N/A'), ('2', 'A'), ('3', 'B+'), ('4', 'B'), ('5', 'C+'), ('6', 'C'), ('7', 'D+'), ('8', 'D'), ('9', 'E'), ('10', 'F')], default='N/A', max_length=100)),
                ('EASC101', models.CharField(choices=[('1', 'N/A'), ('2', 'A'), ('3', 'B+'), ('4', 'B'), ('5', 'C+'), ('6', 'C'), ('7', 'D+'), ('8', 'D'), ('9', 'E'), ('10', 'F')], default='N/A', max_length=100)),
                ('EASC104', models.CharField(choices=[('1', 'N/A'), ('2', 'A'), ('3', 'B+'), ('4', 'B'), ('5', 'C+'), ('6', 'C'), ('7', 'D+'), ('8', 'D'), ('9', 'E'), ('10', 'F')], default='N/A', max_length=100)),
                ('EASC106', models.CharField(choices=[('1', 'N/A'), ('2', 'A'), ('3', 'B+'), ('4', 'B'), ('5', 'C+'), ('6', 'C'), ('7', 'D+'), ('8', 'D'), ('9', 'E'), ('10', 'F')], default='N/A', max_length=100)),
                ('RESULTS', models.FileField(null=True, upload_to='')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('programtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.programtype')),
            ],
        ),
    ]
