# Generated by Django 4.1.5 on 2023-10-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0004_alter_student_choices_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_choices',
            name='ABCS101',
            field=models.CharField(choices=[('N/A', 'N/A'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_choices',
            name='BOTN104',
            field=models.CharField(choices=[('N/A', 'N/A'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_choices',
            name='CHEM113',
            field=models.CharField(choices=[('N/A', 'N/A'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_choices',
            name='CHEM114',
            field=models.CharField(choices=[('N/A', 'N/A'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_choices',
            name='CHEM120',
            field=models.CharField(choices=[('N/A', 'N/A'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_choices',
            name='CHEM122',
            field=models.CharField(choices=[('N/A', 'N/A'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_choices',
            name='DCIT101',
            field=models.CharField(choices=[('N/A', 'N/A'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_choices',
            name='DCIT102',
            field=models.CharField(choices=[('N/A', 'N/A'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_choices',
            name='DCIT103',
            field=models.CharField(choices=[('N/A', 'N/A'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_choices',
            name='DCIT104',
            field=models.CharField(choices=[('N/A', 'N/A'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_choices',
            name='EASC101',
            field=models.CharField(choices=[('N/A', 'N/A'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_choices',
            name='EASC104',
            field=models.CharField(choices=[('N/A', 'N/A'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_choices',
            name='EASC106',
            field=models.CharField(choices=[('N/A', 'N/A'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_choices',
            name='ECON101',
            field=models.CharField(choices=[('N/A', 'N/A'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_choices',
            name='MATH121',
            field=models.CharField(choices=[('N/A', 'N/A'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_choices',
            name='MATH122',
            field=models.CharField(choices=[('N/A', 'N/A'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_choices',
            name='MATH123',
            field=models.CharField(choices=[('N/A', 'N/A'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_choices',
            name='MATH126',
            field=models.CharField(choices=[('N/A', 'N/A'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_choices',
            name='PHYS105',
            field=models.CharField(choices=[('N/A', 'N/A'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_choices',
            name='PHYS106',
            field=models.CharField(choices=[('N/A', 'N/A'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_choices',
            name='PHYS143',
            field=models.CharField(choices=[('N/A', 'N/A'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_choices',
            name='PHYS144',
            field=models.CharField(choices=[('N/A', 'N/A'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_choices',
            name='STAT111',
            field=models.CharField(choices=[('N/A', 'N/A'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_choices',
            name='STAT112',
            field=models.CharField(choices=[('N/A', 'N/A'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='N/A', max_length=100),
        ),
    ]
