# Generated by Django 4.2.6 on 2023-10-09 12:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0005_alter_student_choices_abcs101_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_choices',
            name='Enrolment_Type',
            field=models.CharField(choices=[('Regular', 'Regualar'), ('Fee paying', 'Fee Paying'), ('International', 'International')], default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
